version: 0.2

phases:
  pre_build:
    commands:
      - echo logging in to Docker Hub
      - docker login --username kevlw@amazon.com --password EVAQmqKV2aTkT5
      - echo Logging in to Amazon ECR...
      - aws ecr get-login-password --region ap-southeast-1 | docker login --username AWS --password-stdin 187111385503.dkr.ecr.ap-southeast-1.amazonaws.com
  build:
    commands:
      - echo Build started on `date`
      - echo Building the Docker image...  
      - cd MakanDocker   
      - docker build -t makanrepo .
      - docker tag makanrepo:latest 187111385503.dkr.ecr.ap-southeast-1.amazonaws.com/makanrepo:latest 
      - cd ..
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing the Docker image...
      - docker push 187111385503.dkr.ecr.ap-southeast-1.amazonaws.com/makanrepo:latest
      - echo Writing image definitions file...
      - printf '[{"name":"Makan","imageUri":"187111385503.dkr.ecr.ap-southeast-1.amazonaws.com/makanrepo:latest"}]' > imagedefinitions.json
artifacts:
  files: imagedefinitions.json 